### ISSUE TITLE
grpcat lacks any unit tests.

### ISSUE THREAD

**Issue by adamf** [GyroscopeHQ/grpcat#1]
grpcat doesn't have any unit tests, and needs some.

**Comment by dosvath** [comment]
The following unit test ideas start at basic functionality and progress to the more involved tasks of the program.

**1. Argument Parsing**
The goal of this unit test is to confirm whether the first part of grpcat.py is parsing command line arguments correctly. The test can be expanded to check whether invalid arguments, sequences and formats produce the correct error output, and whether the program is handling exceptions correctly. The test would involve comparing (using assert) the return value of the function with expected output. The error handling tests would involve feeding various types of incorrect input as arguments, and checking if the appropriate error output is as expected. 

**2. Server/RPC Response**
The first part of this unit test would determine whether the connection with the server was successful or has failed and the program terminated. The second part - if there was a successful connection - tests if the response matches the expected value. The expected value, or its features to generate the expected value (the get_hello_request.txt for instance) could be provided to the unit test as input. The test would then determine if the response matches the expected value. 

**3. Timeout and deterministic output**
This unit test would check how long it takes the program to produce the expected response given the input data in the get_hello_request.txt. This would include testing if the program takes too much time (exceeds a limit) and how much time it takes for a particular input, which can be tested multiple times and its duration could be compared, averaged and asserted with an expected value. (This would be useful to see how the input affects the runtime as well.) The second part of this test would be to check whether the program (or response) is deterministic, i.e. produces the same output given the same input multiple times. This could be implemented using a loop and comparing actual vs expected output. If the output differs with the same input one can look for the cause and fix the issue.

**Comment by adamf** [comment]
Thanks @danielOsvath !

I like all the ideas! One thing to make sure is that for #2 you don't require a server be up - eg, you mock the server in the unit test (doing #2 with a server running would be a good integration test, but outside the scope of this issue). 

Thanks!

**Comment by dosvath** [comment]
I have revised test #2 and divided the other tests into the smallest units possible. 

**1. Argument Parsing**
a) Expected Parse
The goal of this unit test is to confirm whether the first part of grpcat.py is parsing command line arguments correctly. The test would involve comparing (using assert) the return value of the parse_args() function with expected output.
b) Errors
Another test can be implemented to check whether invalid arguments, sequences and formats produce the correct error output, and whether the program is handling exceptions correctly. The error handling tests would involve feeding various types of incorrect input as arguments, and checking if the appropriate error output is as expected. 

**2. Server/RPC Response**
This unit test checks whether the output from grpcat using a mock server produces the expected value. The expected outputs could be created manually, or generated based on the get_hello_request.txt, and compared with the grpcat output (the server response). The test inputs for grpcat could be written to the .txt file.

**3. Timeout and deterministic output**
a) Time Limit
This unit test would check how long it takes the program to produce the expected response given the input data in the get_hello_request.txt. This would include testing if the program takes too much time (exceeds a limit).
b) Expected time based on input
This test would check how much time it takes for a particular input, which can be tested multiple times and its duration could be compared, averaged and asserted with an expected value. (This would be useful to see how the input affects the runtime as well.) 
c) Consistent output 
The second test would be to check whether the program (or response) is deterministic, i.e. produces the same output given the same input multiple times. This could be implemented using a loop and comparing actual vs expected output. If the output differs with the same input one can look for the cause and fix the issue.

**Comment by adamf** [comment]
Perfect! Send a pull request and I'l review. Thanks!
